//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SimpleMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AwardActivityContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AwardActivityContext object using the connection string found in the 'AwardActivityContext' section of the application configuration file.
        /// </summary>
        public AwardActivityContext() : base("name=AwardActivityContext", "AwardActivityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AwardActivityContext object.
        /// </summary>
        public AwardActivityContext(string connectionString) : base(connectionString, "AwardActivityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AwardActivityContext object.
        /// </summary>
        public AwardActivityContext(EntityConnection connection) : base(connection, "AwardActivityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblHelpText> tblHelpTexts
        {
            get
            {
                if ((_tblHelpTexts == null))
                {
                    _tblHelpTexts = base.CreateObjectSet<tblHelpText>("tblHelpTexts");
                }
                return _tblHelpTexts;
            }
        }
        private ObjectSet<tblHelpText> _tblHelpTexts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblHelpTexts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblHelpTexts(tblHelpText tblHelpText)
        {
            base.AddObject("tblHelpTexts", tblHelpText);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AwardActivityModel", Name="tblHelpText")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblHelpText : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblHelpText object.
        /// </summary>
        /// <param name="helpTextKey">Initial value of the HelpTextKey property.</param>
        public static tblHelpText CreatetblHelpText(global::System.String helpTextKey)
        {
            tblHelpText tblHelpText = new tblHelpText();
            tblHelpText.HelpTextKey = helpTextKey;
            return tblHelpText;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HelpTextKey
        {
            get
            {
                return _HelpTextKey;
            }
            set
            {
                if (_HelpTextKey != value)
                {
                    OnHelpTextKeyChanging(value);
                    ReportPropertyChanging("HelpTextKey");
                    _HelpTextKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("HelpTextKey");
                    OnHelpTextKeyChanged();
                }
            }
        }
        private global::System.String _HelpTextKey;
        partial void OnHelpTextKeyChanging(global::System.String value);
        partial void OnHelpTextKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HelpText
        {
            get
            {
                return _HelpText;
            }
            set
            {
                OnHelpTextChanging(value);
                ReportPropertyChanging("HelpText");
                _HelpText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HelpText");
                OnHelpTextChanged();
            }
        }
        private global::System.String _HelpText;
        partial void OnHelpTextChanging(global::System.String value);
        partial void OnHelpTextChanged();

        #endregion

    
    }

    #endregion

    
}
